{% set name = "struct-lmm" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4abec1e0fc80335bfbe4a95dd6136a22107efb80572376964b65761aaacc4233

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >3
    - setuptools >=49.6.0
  run:
    - chiscore >=0.2.2
    - glimix-core >=3.1.11
    - numpy >=1.17.4
    - numpy-sugar >=1.5.1
    - pytest >=5
    - pytest-doctestplus >=0.8.0
    - python >3

test:
  imports:
    - struct_lmm
  commands:
    - python -c "import sys; import struct_lmm; sys.exit(struct_lmm.test())"

about:
  home: https://github.com/limix/struct-lmm
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: StructLMM tests for and characterizes loci that interact with environments
  dev_url: https://github.com/limix/struct-lmm

extra:
  recipe-maintainers:
    - Horta
