travis:
  secure:
    BINSTAR_TOKEN: vvnVUPlDC7QpGDG8+CTVYETmnD/6EdXQOvC4OLgPOhy4eOmgFv25+8/HuXuwhXAWDQr7WzycDrTjUKx0wL23QcrssxJia3iMjfqRpvx+lYJM0jLCXpxy/akurxSrCwFMPkFMjVq4dkKWjcSytwAbLXLwwL4ZVIA82wss2IjU4nssfkNKBnpAsswn8sbeZmLewCXpvC3t5MxAVYTiVgcRrHI8svYMc8TXiNSEOZ+c1K5cNZrpjEBPRWAkOgRLR/xotieFrOguwck9QD9l8oC+oGDP/ezYFsnaVBaLTvgu3EOpgOzWqLGONV4LYvEd1Zrp/nz5S7bJ+qbQAe09JP2HA9D3+yRt0uQCe9IpcGmg6Vkn7+7SGBxCdLv7xfQTICm868QMDavDwO8KpgAykQWQLTFDp8CJ9Rxl4OYXW8DunMEeXtu9FDir9wA4J6vMA3XZ+WEUaGQf31IuT1/87vmwYGF2Cia7BAms+xZB52OlGxRtu4pThdivLltPFwu/ZTnuX0TgRzc6aEMvFzcV/38aIWEj4Yyy46wXZem3C1ZGzMJM3g9F43GxmfoGBuzrbOny9Pei2STomwY+TSTopJaaSpoQzWIuz7bzC/6PAcSDIqvOhd2urNzUOuhbqwQtkAKzv4PeKFaAUtk1Am6ccRyC2gEAen+CRESrGJDIL3+lobc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
